# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Jan 19, 2023
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Jan 12, 2023
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Nov 23, 2022
    hooks:
      - id: flake8
        args: ['--ignore=W503,W504,F401,E121,E123,E126,E133']

  - repo: https://github.com/psf/black
    rev: 22.12.0  # Dec 22, 2022
    hooks:
      - id: black
